### ISSUE TITLE
"Perfect" slider curve is used in more cases than 3-point circle

### ISSUE THREAD

**Issue by knah** [ExCellRaD/osuElements#4]
It looks like it's also used for sliders with multiple linear segments, as seen in "Origin" difficulty of this mapset: https://osu.ppy.sh/b/145366

**Comment by ExCellRaD** [comment]
Strange, that seems to be either due to the mapper changing the type manually, or the beatmap file version (which is 11 in this case). I say this because when you save that difficulty from the editor, the type is correctly changed to bezier. 
I can add reading this kind of sliders, but not writing as we don't know exactly what causes it.

**Comment by ExCellRaD** [comment]
Should be fixed now
